[package]
name = "permguard-sdk"
version = "0.1.0"
edition = "2024"
keywords = ["example", "library"]
categories = ["development-tools"]

[lib]
name = "permguard"
crate-type = ["lib"]  # could also include "cdylib", "rlib", etc.

[dependencies]
tonic = "*"
prost = "0.14"
tonic-prost = "*"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "fs"] }
prost-types = "0.14.1"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }

[build-dependencies]
tonic-prost-build = "*"
